### ISSUE TITLE
Open File does not work

### ISSUE THREAD

**Issue by ThFrey** [bitwiseworks/dooble-os2#11]
**Describe the bug**
After selecting the file and Open  ERR_FILE_NOT_FOUND appears

**To Reproduce**
1. Go to 'File...Open File'
2. Click on 'Open....'

**Expected behavior**
an opened file in a tab

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArcaOS 5.0.6
 - Browser Dooble
 - Version 2022.04.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilvanScherrer** [comment]
same as https://github.com/bitwiseworks/dooble-os2/issues/8, so closing this.
