### ISSUE TITLE
automatic opening of submenus of main menu does not propery work

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/dooble-os2#17]
**Describe the bug**
When I single click on the main menu entries, the corresponding submenu will open. When I then move the mouse cursor to the right to the next main menu entries' submenus will open.
However, moving the mouse cursor to the left will not open the submenus.

**To Reproduce**
1. Select very left main menu entry ("File")
2. click on entry, submenu for "File" will open
3. move mouse cursor to the next right menu entry ("Edit")
4. submenu for "Edit" will open
5. move mouse cursor back to "File"
6. submenu for "File" will not open

**Expected behavior**
Mouse cursor move Drag behaviour should be the same in both directions.

**Comment by SilvanScherrer** [comment]
This is a general Qt issue. See https://github.com/bitwiseworks/qtbase-os2/issues/122
