### ISSUE TITLE
Dooble fails to render login entry fields at schwab.com

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/dooble-os2#19]
Dooble does not fully render the login screen for

  https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx?

The userid and password fields are not rendered.

This compares to simple-browser, which renders the fields as expected, 
although login attempts failed.

The venerable firefox 45.9 renders the login fields as expected and logins work.

Dooble was tested running

  dooble-2022.04.04-1.oc00.pentium4.rpm

and

  09-08-22  13:43     271,973,910    124  Qt5WebC.dll
  e20fd297255d1709f76ec2b41e9ddec2 *Qt5WebC.dll

**Comment by StevenLevine** [comment]
This issue persists with the 2022.10.15 build.

**Comment by dmik** [comment]
I've been told by Roderick that you are also experiencing the very same issue with Dooble and Qt 6 on Linux. If this is true, then it's not an OS/2 specific problem but rather a Dooble one.

**Comment by SilvanScherrer** [comment]
I tried latest Dooble on Ubuntu and schwab.com doesn't render the login page. So I doubt it's a port issue as well.

**Comment by StevenLevine** [comment]
Paul's testing revealed the same thing.

Since it's not specific to our port, I will attempt to track down where
best to report this. Since all versions of dooble fail, I'm going to start
with a issue on the dooble github site.  Either they will report it
upstream or provide some guidance on where this should be reported
upstream.

**Comment by StevenLevine** [comment]
Recent dooble builds have resolved this issue.  Dave's 2023-04-20 and 2023-05-31 builds now handle the site properly.
