### ISSUE TITLE
Trying to print crashes Dooble.

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/dooble-os2#5]
Trying to print by clicking on the 'hamburger' icon (3 horizontal lines) in upper right corner, then choose 'Print' brings up a tiny window that needs to be enlarged to see anything. Once enlarged, choosing 'Print' crashes Dooble (disappears from screen) and an exceptq report is created (attached). Happens in both single and multi-process modes.
[62667310-008e_05-DOOBLE-exceptq.txt](https://github.com/bitwiseworks/dooble-os2/files/8555296/62667310-008e_05-DOOBLE-exceptq.txt)

**Comment by dmik** [comment]
The crash looks familiar, see https://github.com/bitwiseworks/qtwebengine-os2/issues/11. Closing this in favour of that one. Printing has never been tested on OS/2 so far.
