### ISSUE TITLE
Browser identified as "unknown"

### ISSUE THREAD

**Issue by MartinVieregg** [bitwiseworks/dooble-os2#7]
The browser is shown as "Unknown" for the Server. After getting an Verification code E-Mail from Github,

A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.

Device: Chrome on Unknown
Verification code: ....

It seems that the OS name string is not set.

**Comment by DavidMcKenna** [comment]
No problem here with the rpm version... try resetting the user agent in 'Edit' -> 'Settings' -> 'User Agent'.

**Comment by SilvanScherrer** [comment]
already fixed, please see ticket https://github.com/bitwiseworks/dooble-os2/issues/3
