### ISSUE TITLE
local file name with drive letter X: not accepted

### ISSUE THREAD

**Issue by MartinVieregg** [bitwiseworks/dooble-os2#8]
To open a local file, you can only access files on the system drive. Drive letters X: are not accepted.
Accepted is:
file:///MyDirOnSysDrive/MyFile.html
Not Accpeted is:
file:///X:/MyDirOnDriveX/MyFile.html

It seems that the necessary OS/2 or Windows specific code is simply not implemented yet. I have tested the Dooble Windows version which works fine. I assume it is only necessary to use the Windows specific code for local file names.

**Comment by DavidMcKenna** [comment]
I get 'Your file was not found' no matter what drive used...

**Comment by Greggk** [comment]
I have attached a patch which might address PATH issues

**Comment by dmik** [comment]
Thanks for dealing with that and for the patch. But it's clearly a wrong place for this ticket because it's qtwebengine code, not Dooble. Will close this in favour of https://github.com/bitwiseworks/qtwebengine-os2/issues/7.
